export const SET_TODO_LIST = 'SET_TODO_LIST';
export const ADD_TO_TODO_LIST = 'ADD_TO_TODO_LIST';
export const UPDATE_TODO_ITEM = 'UPDATE_TODO_ITEM';
export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM';
export const SORT_TODO_LIST = 'SORT_TODO_LIST';
export const SEARCH_TODO_ITEM = 'SEARCH_TODO_ITEM';
export const RESET_TODO_LIST = 'RESET_TODO_LIST';

export const SET_INPUT_VALUE = 'SET_INPUT_VALUE';
export const RESET_INPUT_VALUE = 'RESET_INPUT_VALUE';
